version: '2'
services:
    nicolas-app:
        image: nicolas
        external_links:
            - kafka:kafka
            - zookeeper:zookeeper
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
    kafka:
        extends:
            file: kafka.yml
            service: kafka
        environment:
            - KAFKA_ADVERTISED_HOST_NAME=kafka
    zookeeper:
        extends:
            file: kafka.yml
            service: zookeeper
