version: '2'
services:
    nicolas-app:
        image: nicolas
        external_links:
            - kafka:kafka
            - zookeeper:zookeeper
            - grafana:grafana
            - prometheus:prometheus
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
    kafka:
        extends:
            file: kafka.yml
            service: kafka
        environment:
            - KAFKA_ADVERTISED_HOST_NAME=kafka
    zookeeper:
        extends:
            file: kafka.yml
            service: zookeeper
    grafana:
        extends:
            file: kafka.yml
            service: grafana
    prometheus:
        extends:
            file: kafka.yml
            service: prometheus
            